Implementierungsleitfaden für KIM E-Rezept
gematik/spec-erezept-medicationrequest-communication pull request #26
Opened 2023-04-17 07:48 UTC by florianschoffke

2023-04-17 15:54 UTC, SvenSommer requested changes
Sehr gute Arbeit und eine gute Grundlage für zukünftige IGs.

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/toc.yaml
> +- name: Home
Bitte spezifischer!

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Datenobjekte/MedicationRequest/3_Profil.page.md
> +Die folgende FHIR Ressource stellt eine Ressource bereit, die als Trägerobjekt für medizinische Informationen dient. Sie ist von der Profilierung an die [KBV_PR_ERP_Prescription](https://simplifier.n
Sie ist an die [KBV_PR_ERP_Prescription](https://simplifier.net/erezept/kbvprerpprescription) Profilierung angelehnt, um Informationen so einfach wie möglich in die Verordnung zu übernehmen.

2023-04-17 15:54 UTC, SvenSommer commented on Resources/fsh-generated/resources/StructureDefinition-service-request-prescription-request.json
> +            "map": "Pateiteninformationen"
Typo

2023-04-17 15:54 UTC, SvenSommer commented on Resources/input/fsh/mappings/prescription-sr-mapping.fsh
> +* subject -> "Pateiteninformationen"
Typo

2023-04-17 15:54 UTC, SvenSommer commented on Resources/input/fsh/valuesets/KIMDienstkennungVS.fsh
>  Id: kim-dienstkennung-vs
Das muss noch raus, oder?

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/0-Index.page.md
> +# {{page-title}}
leere Seite?!

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/1-Fachliche-Beschreibung.page.md
> +Eine detaillierte fachliche Beschreibung ist hier zu finden [gemF_eRp_KIM](//TODO).
Was erwartest wir hier vom KIM Team?

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/2.1-Anfragender-an-Verordnenden.page.md
> +Folgende Profile sind für diesen Übertragungsweg zu nutzen und im {{link:https://gematik.de/fhir/erpmedreqcom/StructureDefinition/bundle-message-container}} einzubetten:
Link funktioniert bei dir? Ich hatte hier Probleme
![image](https://user-images.githubusercontent.com/10847488/232539215-ee6adb39-3d02-4ba5-8b13-7aa4ea75ea2f.png)

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/2.1-Anfragender-an-Verordnenden.page.md
> +|{{pagelink:Home/Datenobjekte/MessageHeader}}|BundleMessageContainer.entry||
Springt man zu diesen Seiten, fehlt eine Erklärende Überschrift, auf welcher Seite man sich nun befindet. Hier steht "Index" als Überschrift. Ich hätte "MessageHeader" erwartet

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/2.3-Anfragender-an-Apotheke.page.md
> +angegeben. Falls die Apotheke den Vorgang noch nicht bearbeitet hat ist der Vorgang abzubrechen. Wenn die Apotheke das E-Rezept bereits über $accept in den Status "in Abgabe (gesperrt)" gestellt hat
Komma: Falls die Apotheke den Vorgang noch nicht bearbeitet hat, ist

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/3_Klaerfall/1-Fachliche-Beschreibung.page.md
> +## {{page-title}}
Kann weg?

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/3_Klaerfall/2-Event-Codes.page.md
> +## {{page-title}}
Kann weg?

2023-04-17 15:54 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/3_Klaerfall/3-Verwendung-Ressourcen.page.md
> +## {{page-title}}
Kann weg?

2023-04-18 05:08 UTC, florianschoffke commented on Resources/input/fsh/valuesets/KIMDienstkennungVS.fsh
>  Id: kim-dienstkennung-vs
Naja die id muss schon vorhanden sein. Ich habe noch "insert MetaValueSet()" eingefügt. 
Würde die Benennung aber so lassen. Dadurch ist klar, dass es sich um Codes aus dem CS handelt.

2023-04-18 05:10 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/0-Index.page.md
> +# {{page-title}}
Ja das wird dann beim Rendern zusammengeschraubt.
Kann aber sein, dass es dafür andere best-practices gibt. Hast du einen Vorschlag/ Beispiel?

2023-04-18 05:11 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/1-Fachliche-Beschreibung.page.md
> +Eine detaillierte fachliche Beschreibung ist hier zu finden [gemF_eRp_KIM](//TODO).
Das wird der Link zum FeatureDokukent. Das müsste eigentlich vorher veröffentlicht werden. Und da verweisen wir dann drauf.

2023-04-18 05:13 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/2.1-Anfragender-an-Verordnenden.page.md
> +Folgende Profile sind für diesen Übertragungsweg zu nutzen und im {{link:https://gematik.de/fhir/erpmedreqcom/StructureDefinition/bundle-message-container}} einzubetten:
Das sind dann noch Abhängigkeiten, die wir auflösen müssen. Entweder ist da was bei den dependencies nicht richtig oder der Link zu atf hat sich geändert.
Das würde ich vorschlagen fixen wir wenn wir das auf dem richtigen Simplifier Repo haben. Dann müssen wir es da nur ein mal machen.

2023-04-18 05:18 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/2.1-Anfragender-an-Verordnenden.page.md
> +|{{pagelink:Home/Datenobjekte/MessageHeader}}|BundleMessageContainer.entry||
fixed

2023-04-18 05:33 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Identifier/GroupIdentifier/0_Index.page.md
> +## {{page-title}}
Ja ist als Platzhalter, sieht auf Dateiebene evtl ulkig aus, aber würde es als "pattern" gerne so behalten

2023-04-18 05:54 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Identifier/PreDisIdentifier/0_Index.page.md
> +## {{page-title}}
Lass uns da mal drüber reden, aber dient m.E. als Überschrift für die Seite. Habe es entsprechend angepasst, dass der Titel angezeigt wird anstatt "Index"

2023-04-18 05:57 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Identifier/RequestIdentifier/1_Motivation.page.md
> +## {{page-title}}
Ich wäre für ein einheitliches Pattern. Also das so zu lassen, weil es bei "Datenobjekte" so ist

2023-04-18 06:00 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/UebergreifendeFestlegungen/File-Format.page.md
> +Zur erhöhten Interoperabilität auch mit Blick auf die Zukunft mit vermehrtem Einsatz von mobilen Endgeräten SOLL das System auch das Austauschformat [JSON](http://hl7.org/fhir/json.html) unterstützen
Warum?

2023-04-18 06:01 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/UebergreifendeFestlegungen/File-Format.page.md
> +Je nach Transportmedium MUSS nach Möglichkeit die Information des gewählten Dateiformats übermittelt werden, z.B. in Form eines HTTP-Headers.
War nur Beispielhaft, weil es ja unabhängig vom Protokoll ist. Bei KIM sollte dann, wenn es die Möglichkeit gibt, ein KIM-Header angegeben werden. Ich wollte nur sasgen, dass man das über das Transportmedium mitgeben können muss welches Datenformat verwendet wird.

2023-04-18 06:02 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/UebergreifendeFestlegungen/File-Format.page.md
> +Zur erhöhten Interoperabilität auch mit Blick auf die Zukunft mit vermehrtem Einsatz von mobilen Endgeräten SOLL das System auch das Austauschformat [JSON](http://hl7.org/fhir/json.html) unterstützen
Wenn dann später eine Rezeptanforderung über eine App kommt wäre es vorausschauend jetzt schon zu sagen, dass JSON auch akzeptiert werden muss.

2023-04-18 06:05 UTC, florianschoffke commented on guides/ig-rezeptanforderung/style/master.html
> +        <title>{{ guide-title }}</title>
Was fändest du besser? Wir können auch den Titel des ILF ändern

2023-04-18 06:11 UTC, florianschoffke commented on Resources/input/fsh/valuesets/KIMDienstkennungVS.fsh
>  Id: kim-dienstkennung-vs
die id muss bleiben. 
Aber ich habe es umbenannt analog zu atf

2023-04-18 08:03 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/1-Fachliche-Beschreibung.page.md
> +Eine detaillierte fachliche Beschreibung ist hier zu finden [gemF_eRp_KIM](//TODO).
Ich verstehe nicht, meinst du das App Transport Framework? Da steht 'gemF_eRp_KIM' welches Feature von KIM meinst du da?

2023-04-18 08:05 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Identifier/GroupIdentifier/0_Index.page.md
> +## {{page-title}}
Bitte die Hierarchie der Überschriften beachten.

2023-04-18 08:07 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/Identifier/PreDisIdentifier/0_Index.page.md
> +## {{page-title}}
Hier scheint auch die Herarchie nicht zu passen

2023-04-18 08:15 UTC, SvenSommer commented on guides/ig-rezeptanforderung/Home/UebergreifendeFestlegungen/File-Format.page.md
> +Zur erhöhten Interoperabilität auch mit Blick auf die Zukunft mit vermehrtem Einsatz von mobilen Endgeräten SOLL das System auch das Austauschformat [JSON](http://hl7.org/fhir/json.html) unterstützen
Für die Industrie ist es leichter, wenn sie nur ein Format implementieren müssen. Momentan gibt es keine Akzeptanz für einen Mehraufwand. Ich bin dafür wir legen uns auf XML fest. Die Kommunkation mit der App kann als Sonderfall bewertet werden, den ich eher bei App-Team auflösen würde.

2023-04-18 08:36 UTC, SvenSommer commented on guides/ig-rezeptanforderung/style/master.html
> +        <title>{{ guide-title }}</title>
Solange es keine generischen Titel wie "Home" oder "Index" gibt, sondern Titel die zum Seiteninhalt passen, bin ich zufrieden

2023-04-18 08:55 UTC, SvenSommer commented on Resources/input/fsh/mappings/prescription-sr-mapping.fsh
> +* subject -> "Pateiteninformationen"
Für mich steht da noch "Pateiteninformationen" und nicht "Patienteninformationen"

2023-04-18 12:56 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/1-Fachliche-Beschreibung.page.md
> +Eine detaillierte fachliche Beschreibung ist hier zu finden [gemF_eRp_KIM](//TODO).
https://polarion.int.gematik.de/polarion/#/project/Mainline_OPB1/wiki/E-Rezept/[gemF_eRp_KIM](https://polarion.int.gematik.de/polarion/#/project/Mainline_OPB1/wiki/E-Rezept/gemF_eRp_KIM)

2023-04-18 12:57 UTC, florianschoffke commented on guides/ig-rezeptanforderung/style/master.html
> +        <title>{{ guide-title }}</title>
Das ist mE der Title, der oben im Browser im Tab steht. Da steht aktuell "IG-Rezeptanforderung". 
Ist das okay?

2023-04-20 04:50 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/Anwendungsfaelle/1_Rezeptanforderung/1-Fachliche-Beschreibung.page.md
> +Eine detaillierte fachliche Beschreibung ist hier zu finden [gemF_eRp_KIM](//TODO).
Habe einen Link auf das Fachportal mit der Seite der Featuredokumente verwiesen

2023-04-20 04:52 UTC, florianschoffke commented on guides/ig-rezeptanforderung/Home/UebergreifendeFestlegungen/File-Format.page.md
> +Zur erhöhten Interoperabilität auch mit Blick auf die Zukunft mit vermehrtem Einsatz von mobilen Endgeräten SOLL das System auch das Austauschformat [JSON](http://hl7.org/fhir/json.html) unterstützen
Hinweis zu JSON ist entfernt

2023-04-20 11:22 UTC, SvenSommer requested changes

2023-04-20 11:22 UTC, SvenSommer commented on Resources/input/fsh/valuesets/ServiceIdentifierVS.fsh
> +Title: "E-Rezept KIM-Dienstkennung"
"KIM" muss raus!

2023-04-20 17:27 UTC, SvenSommer approved these changes

2023-04-21 05:07 UTC, merged